# Tensorflow2.0 小练习

In [12]:
import tensorflow as tf
import numpy as npm

## 实现softmax函数

![title](img/Softmax.png)

In [13]:
#np
def softmax(x):
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis=1, keepdims=True)
    prob_x = x_exp / x_sum
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data) - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001  #去掉了.numpy()

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [14]:
def softmaxF(x):
    x_exp = tf.math.exp(x)
    x_sum = tf.reduce_sum(x_exp, axis=1, keepdims=True)
    prob_x = x_exp / x_sum
    return prob_x
(softmaxF(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [15]:
## 实现sigmoid函数

![title](img/Sigmoid.png)

In [16]:
#np
def sigmoid(x):
    x =1 + (1 / np.exp(x))
    prob_x = 1 / x
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data) - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001  #去掉了.numpy()

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [17]:
#tf
def sigmoidF(x):
    prob_x =1/(1+ (1/tf.math.exp(x)))
    return prob_x

test_data = np.random.normal(size=[10, 5])
# print(tf.nn.softmax(test_data, axis=-1).numpy(),'T')
(sigmoidF(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

![title](img/softmaxH.png)

In [18]:
#np
def softmax_ce(x, label):
    loss = -np.sum(np.nan_to_num(label*np.log(x)),axis=1) 
    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.
((tf.nn.softmax_cross_entropy_with_logits(label, test_data) #tf.reduce_mean()会把张量格式改了，很奇怪!
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [19]:
#tf
def softmax_ceF(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    losses = -tf.reduce_sum(label*tf.math.log(x),axis=1)
    loss = tf.reduce_mean(losses)
    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ceF(prob, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

![title](img/sigmoidH.png)

In [20]:
#np
def sigmoid_ce(x, label):
    loss = -np.sum(np.nan_to_num(label*np.log(x)+(1-label)*np.log(1-x)))
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
a = tf.nn.sigmoid_cross_entropy_with_logits(label, test_data).numpy()
((np.sum(a)- sigmoid_ce(prob, label))**2 < 0.0001)                       

True

In [21]:
#tf
def sigmoid_ceF(x, label):
    losses = -tf.reduce_sum(label*tf.math.log(x)+(1.-label)*tf.math.log(1-x))/len(x)
    loss = tf.reduce_mean(losses)
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ceF(prob, label))**2 < 0.0001).numpy()

True